"""Crear tabla alumnos

Revision ID: 3b665035ebd7
Revises: 
Create Date: 2026-02-21 09:10:37.655045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b665035ebd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=10), nullable=True))
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('apellido',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('telefono')

    op.create_table('usuario',
    sa.Column('idUsuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('contrasenia', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('rol', mysql.ENUM('Bibliotecario', 'Alumno'), nullable=True),
    sa.Column('universidad', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('estatus', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('fecha_registro', mysql.DATETIME(), server_default=sa.text('(curdate())'), nullable=True),
    sa.PrimaryKeyConstraint('idUsuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
